package pt.ktc.openk.pos.customers;

import java.util.Arrays;
import java.util.List;

// Esta classe 
public class CountryHelper {
	
	private static Country[] m_CountryList={
			new Country("Afeganistão",	"AF"),
			new Country("Ilhas Aland",	"AX"),
			new Country("Albânia",	"AL"),
			new Country("Argélia",	"DZ"),
			new Country("Samoa Americana",	"AS"),
			new Country("Andorra",	"AD"),
			new Country("Angola",	"AO"),
			new Country("Anguilla",	"AI"),
			new Country("Antártida",	"AQ"),
			new Country("Antígua e Barbuda",	"AG"),
			new Country("Argentina",	"AR"),
			new Country("Armênia",	"AM"),
			new Country("Aruba",	"AW"),
			new Country("Austrália",	"AU"),
			new Country("Áustria",	"AT"),
			new Country("Azerbaijão",	"AZ"),
			new Country("Bahamas",	"BS"),
			new Country("Bahrein",	"BH"),
			new Country("Bangladesh",	"BD"),
			new Country("Barbados",	"BB"),
			new Country("Belarus",	"BY"),
			new Country("Bélgica",	"BE"),
			new Country("Belize",	"BZ"),
			new Country("Benin",	"BJ"),
			new Country("Bermudas",	"BM"),
			new Country("Butão",	"BT"),
			new Country("Bolívia",	"BO"),
			new Country("Bósnia-Herzegóvina",	"BA"),
			new Country("Botsuana",	"BW"),
			new Country("Ilha Bouvet (Território da Noruega)",	"BV"),
			new Country("Brasil",	"BR"),
			new Country("Território Britânico do Oceano índico",	"IO"),
			new Country("Brunei",	"BN"),
			new Country("Bulgária",	"BG"),
			new Country("Burkina Fasso",	"BF"),
			new Country("Burundi",	"BI"),
			new Country("Camboja",	"KH"),
			new Country("Camarões",	"CM"),
			new Country("Canadá",	"CA"),
			new Country("Cabo Verde",	"CV"),
			new Country("Ilhas Cayman",	"KY"),
			new Country("República Centro-Africana",	"CF"),
			new Country("Chade",	"TD"),
			new Country("Chile",	"CL"),
			new Country("China",	"CN"),
			new Country("Ilha Natal",	"CX"),
			new Country("Ilhas Cocos",	"CC"),
			new Country("Colômbia",	"CO"),
			new Country("Ilhas Comores",	"KM"),
			new Country("Congo",	"CG"),
			new Country("República Democrática do Congo (ex-Zaire)",	"CD"),
			new Country("Ilhas Cook",	"CK"),
			new Country("Costa Rica",	"CR"),
			new Country("Costa do Marfim",	"CI"),
			new Country("Croácia (Hrvatska)",	"HR"),
			new Country("Cuba",	"CU"),
			new Country("Chipre",	"CY"),
			new Country("República Tcheca",	"CZ"),
			new Country("Dinamarca",	"DK"),
			new Country("Djibuti",	"DJ"),
			new Country("Dominica",	"DM"),
			new Country("República Dominicana",	"DO"),
			new Country("Equador",	"EC"),
			new Country("Egito",	"EG"),
			new Country("El Salvador",	"SV"),
			new Country("Guiné Equatorial",	"GQ"),
			new Country("Eritréia",	"ER"),
			new Country("Estônia",	"EE"),
			new Country("Etiópia",	"ET"),
			new Country("Ilhas Faroes",	"FO"),
			new Country("Ilhas Falkland (Malvinas)",	"FK"),
			new Country("Fiji",	"FJ"),
			new Country("Finlândia",	"FI"),
			new Country("França",	"FR"),
			new Country("Guiana Francesa",	"GF"),
			new Country("Polinésia Francesa",	"PF"),
			new Country("Territórios do Sul da França",	"TF"),
			new Country("Gabão",	"GA"),
			new Country("Gâmbia",	"GM"),
			new Country("Geórgia",	"GE"),
			new Country("Alemanha",	"DE"),
			new Country("Gana",	"GH"),
			new Country("Gibraltar",	"GI"),
			new Country("Grécia",	"GR"),
			new Country("Groelândia",	"GL"),
			new Country("Granada",	"GD"),
			new Country("Guadalupe",	"GP"),
			new Country("Guam (Território dos Estados Unidos)",	"GU"),
			new Country("Guatemala",	"GT"),
			new Country("Guernsey",	"GG"),
			new Country("Guiné",	"GN"),
			new Country("Guiné-Bissau",	"GW"),
			new Country("Guiana",	"GY"),
			new Country("Haiti",	"HT"),
			new Country("Ilhas Heard e McDonald (Território da Austrália)",	"HM"),
			new Country("Honduras",	"HN"),
			new Country("Hong Kong",	"HK"),
			new Country("Hungria",	"HU"),
			new Country("Islândia",	"IS"),
			new Country("Índia",	"IN"),
			new Country("Indonésia",	"ID"),
			new Country("Irã",	"IR"),
			new Country("Iraque",	"IQ"),
			new Country("Irlanda",	"IE"),
			new Country("Ilha do Homem",	"IM"),
			new Country("Israel",	"IL"),
			new Country("Itália",	"IT"),
			new Country("Jamaica",	"JM"),
			new Country("Japão",	"JP"),
			new Country("Jersey",	"JE"),
			new Country("Jordânia",	"JO"),
			new Country("Cazaquistão",	"KZ"),
			new Country("Kênia",	"KE"),
			new Country("Kiribati",	"KI"),
			new Country("Coréia do Norte",	"KP"),
			new Country("Coréia do Sul",	"KR"),
			new Country("Kuait",	"KW"),
			new Country("Kyrgyzstan",	"KG"),
			new Country("Laos",	"LA"),
			new Country("Látvia",	"LV"),
			new Country("Líbano",	"LB"),
			new Country("Lesoto",	"LS"),
			new Country("Libéria",	"LR"),
			new Country("Líbia",	"LY"),
			new Country("Liechtenstein",	"LI"),
			new Country("Lituânia",	"LT"),
			new Country("Luxemburgo",	"LU"),
			new Country("Macau",	"MO"),
			new Country("Macedônia (República Yugoslava)",	"MK"),
			new Country("Madagascar",	"MG"),
			new Country("Malaui",	"MW"),
			new Country("Malásia",	"MY"),
			new Country("Maldivas",	"MV"),
			new Country("Mali",	"ML"),
			new Country("Malta",	"MT"),
			new Country("Ilhas Marshall",	"MH"),
			new Country("Martinica",	"MQ"),
			new Country("Mauritânia",	"MR"),
			new Country("Maurício",	"MU"),
			new Country("Mayotte",	"YT"),
			new Country("Mexico",	"MX"),
			new Country("Micronésia",	"FM"),
			new Country("Moldova",	"MD"),
			new Country("Mônaco",	"MC"),
			new Country("Mongólia",	"MN"),
			new Country("Montenegro",	"ME"),
			new Country("Montserrat",	"MS"),
			new Country("Marrocos",	"MA"),
			new Country("Moçambique",	"MZ"),
			new Country("Myanma (Ex-Burma)",	"MM"),
			new Country("Namíbia",	"NA"),
			new Country("Nauru",	"NR"),
			new Country("Nepal",	"NP"),
			new Country("Holanda",	"NL"),
			new Country("Antilhas Holandesas",	"AN"),
			new Country("Nova Caledônia",	"NC"),
			new Country("Nova Zelândia",	"NZ"),
			new Country("Nicarágua",	"NI"),
			new Country("Níger",	"NE"),
			new Country("Nigéria",	"NG"),
			new Country("Niue",	"NU"),
			new Country("Ilhas Norfolk",	"NF"),
			new Country("Ilhas Marianas do Norte",	"MP"),
			new Country("Noruega",	"NO"),
			new Country("Omã",	"OM"),
			new Country("Paquistão",	"PK"),
			new Country("Palau",	"PW"),
			new Country("Territórios Palestinos Ocupados",	"PS"),
			new Country("Panamá",	"PA"),
			new Country("Papua-Nova Guiné",	"PG"),
			new Country("Paraguai",	"PY"),
			new Country("Peru",	"PE"),
			new Country("Filipinas",	"PH"),
			new Country("Ilha Pitcairn",	"PN"),
			new Country("Polônia",	"PL"),
			new Country("Portugal",	"PT"),
			new Country("Porto Rico",	"PR"),
			new Country("Qatar",	"QA"),
			new Country("Ilha Reunião",	"RE"),
			new Country("Romênia",	"RO"),
			new Country("Federação Russa",	"RU"),
			new Country("Ruanda",	"RW"),
			new Country("São Bartolomeu",	"BL"),
			new Country("Santa Helena",	"SH"),
			new Country("São Cristóvão e Névis",	"KN"),
			new Country("Santa Lúcia",	"LC"),
			new Country("São Martim",	"MF"),
			new Country("St. Pierre and Miquelon",	"PM"),
			new Country("Saint Vincente e Granadinas",	"VC"),
			new Country("Samoa Ocidental",	"WS"),
			new Country("San Marino",	"SM"),
			new Country("São Tomé e Príncipe",	"ST"),
			new Country("Arábia Saudita",	"SA"),
			new Country("Senegal",	"SN"),
			new Country("Sérvia",	"RS"),
			new Country("Ilhas Seychelles",	"SC"),
			new Country("Serra Leoa",	"SL"),
			new Country("Cingapura",	"SG"),
			new Country("Eslováquia",	"SK"),
			new Country("Eslovênia",	"SI"),
			new Country("Ilhas Solomão",	"SB"),
			new Country("Somália",	"SO"),
			new Country("África do Sul",	"ZA"),
			new Country("Ilhas Geórgia do Sul e Sandwich do Sul",	"GS"),
			new Country("Espanha",	"ES"),
			new Country("Sri Lanka",	"LK"),
			new Country("Sudão",	"SD"),
			new Country("Suriname",	"SR"),
			new Country("Ilhas Svalbard e Jan Mayen",	"SJ"),
			new Country("Suazilândia",	"SZ"),
			new Country("Suécia",	"SE"),
			new Country("Suíça",	"CH"),
			new Country("Síria",	"SY"),
			new Country("Taiwan",	"TW"),
			new Country("Tadjiquistão",	"TJ"),
			new Country("Tanzânia",	"TZ"),
			new Country("Tailândia",	"TH"),
			new Country("Timor Leste (Ex-East Timor)",	"TL"),
			new Country("Togo",	"TG"),
			new Country("Ilhas Tokelau",	"TK"),
			new Country("Tonga",	"TO"),
			new Country("Trinidad and Tobago",	"TT"),
			new Country("Tunísia",	"TN"),
			new Country("Turquia",	"TR"),
			new Country("Turcomenistão",	"TM"),
			new Country("Ilhas Turks e Caicos",	"TC"),
			new Country("Tuvalu",	"TV"),
			new Country("Uganda",	"UG"),
			new Country("Ucrânia",	"UA"),
			new Country("Emirados Árabes Unidos",	"AE"),
			new Country("Grã-Bretanha (Reino Unido, UK)",	"GB"),
			new Country("Estados Unidos",	"US"),
			new Country("Ilhas Menores dos Estados Unidos",	"UM"),
			new Country("Uruguai",	"UY"),
			new Country("Uzbequistão",	"UZ"),
			new Country("Vanuatu",	"VU"),
			new Country("Vaticano",	"VA"),
			new Country("Venezuela",	"VE"),
			new Country("Vietnam",	"VN"),
			new Country("Ilhas Virgens (Inglaterra)",	"VG"),
			new Country("Ilhas Virgens (Estados Unidos)",	"VI"),
			new Country("Ilhas Wallis e Futuna",	"WF"),
			new Country("Saara Ocidental (Ex-Spanish Sahara)",	"EH"),
			new Country("Iêmen",	"YE"),
			new Country("Zâmbia",	"ZM"),
			new Country("Zimbábue",	"ZW")
	};
	
	private static List m_CountryOrderedList=null;
	
	public static List getCountryList() {
		if (m_CountryOrderedList==null) {
			Arrays.sort(m_CountryList);
			m_CountryOrderedList=Arrays.asList(m_CountryList);
			
		}
		return m_CountryOrderedList;
	}
	
	public static boolean checkCountryCode(String cc) {
		boolean found=false;
		if (cc==null) return false;
		for (Country c:m_CountryList) {
			if (((String)c.getKey()).compareTo(cc)==0) {
				found=true;
				break;
			}
		}
		return found;
	}

}
