SELECT RECEIPTS.DATENEW, PRODUCTS.REFERENCE, PRODUCTS.NAME, (PRODUCTS.PRICESELL*(1+TAXES.RATE)) AS PVPUNIT, SUM(TICKETLINES.UNITS) AS UNITS, 
SUM(TICKETLINES.UNITS * (TICKETLINES.PRICE*(1+TAXES.RATE))) AS TOTALPVP
FROM RECEIPTS, TICKETS, TAXES, TICKETLINES LEFT OUTER JOIN PRODUCTS ON TICKETLINES.PRODUCT = PRODUCTS.ID 
WHERE RECEIPTS.ID = TICKETS.ID AND TICKETS.ID = TICKETLINES.TICKET 
 AND TICKETLINES.TAXID=TAXES.ID AND TICKETS.TICKETTYPE<>3 
 AND RECEIPTS.DATENEW>=TO_DATE('2013-05-03', 'YYYY-MM-DD HH24:MI:SS') 
 AND RECEIPTS.DATENEW<=TO_DATE('2013-05-04', 'YYYY-MM-DD HH24:MI:SS')
 GROUP BY RECEIPTS.DATENEW, PRODUCTS.REFERENCE, PRODUCTS.NAME, PRODUCTS.PRICESELL, TAXES.RATE ORDER BY PRODUCTS.NAME

SELECT tickets.tickettype, PRODUCTS.REFERENCE, PRODUCTS.NAME, (PRODUCTS.PRICESELL*(1+TAXES.RATE)) AS PVPUNIT, SUM(TICKETLINES.UNITS) AS UNITS, 
SUM(TICKETLINES.UNITS * (TICKETLINES.PRICE*(1+TAXES.RATE))) AS TOTALPVP
FROM RECEIPTS, TICKETS, TAXES, TICKETLINES LEFT OUTER JOIN PRODUCTS ON TICKETLINES.PRODUCT = PRODUCTS.ID 
WHERE RECEIPTS.ID = TICKETS.ID AND TICKETS.ID = TICKETLINES.TICKET 
 AND TICKETLINES.TAXID=TAXES.ID AND TICKETS.TICKETTYPE<>3 
 AND RECEIPTS.DATENEW>=TO_DATE('2013-04-02', 'YYYY-MM-DD HH24:MI:SS') 
 AND RECEIPTS.DATENEW<=TO_DATE('2013-05-03', 'YYYY-MM-DD HH24:MI:SS')
 GROUP BY tickets.tickettype, PRODUCTS.REFERENCE, PRODUCTS.NAME, PRODUCTS.PRICESELL, TAXES.RATE ORDER BY PRODUCTS.NAME
