-- Remover transacoes
DELETE FROM TICKETLINES; -- ok
DELETE FROM TAXLINES; -- ok  
DELETE FROM TICKETS; -- ok
DELETE FROM PAYMENTS; -- ok
DELETE FROM RECEIPTS; -- ok
DELETE FROM SHAREDTICKETS; -- ok
DELETE FROM STOCKCURRENT; 
DELETE FROM STOCKDIARY; -- ok
DELETE FROM CLOSEDCASH; -- ok
DELETE FROM SIGNATURES; -- OK

-- actualizar dados de inventario
UPDATE STOCKCURRENT SET UNITS = 0;
UPDATE CUSTOMERS SET CURDATE = NULL; 
UPDATE CUSTOMERS SET CURDEBT = 0;

-- reset das sequencias de numeracao
DELETE FROM DOCS_IDS;
-- RECEIPT_NORMAL = 0;
INSERT INTO DOCS_IDS(TICKETTYPE, LAST_TICKETID) VALUES(0, 0);
-- RECEIPT_REFUND = 1;
INSERT INTO DOCS_IDS(TICKETTYPE, LAST_TICKETID) VALUES(1, 0);
-- RECEIPT_PAYMENT = 2;
INSERT INTO DOCS_IDS(TICKETTYPE, LAST_TICKETID) VALUES(2, 0);
-- RECEIPT_PREVIEW = 3; 
INSERT INTO DOCS_IDS(TICKETTYPE, LAST_TICKETID) VALUES(3, 0);
-- RECEIPT_INVOICE = 4; 
INSERT INTO DOCS_IDS(TICKETTYPE, LAST_TICKETID) VALUES(4, 0);
