-- Remover transacoes
DELETE FROM TICKETLINES; -- ok
DELETE FROM TAXLINES; -- ok  
DELETE FROM TICKETS; -- ok
DELETE FROM PAYMENTS; -- ok
DELETE FROM RECEIPTS; -- ok
DELETE FROM SHAREDTICKETS; -- ok
DELETE FROM STOCKCURRENT; 
DELETE FROM STOCKDIARY; -- ok
DELETE FROM CLOSEDCASH; -- ok
DELETE FROM SIGNATURES; -- OK

-- actualizar dados de inventario
UPDATE STOCKCURRENT SET UNITS = 0;
UPDATE CUSTOMERS SET CURDATE = NULL; 
UPDATE CUSTOMERS SET CURDEBT = 0;

-- reset das sequencias de numeracao
ALTER SEQUENCE TICKETSNUM RESTART WITH 1; 
ALTER SEQUENCE TICKETSNUM_REFUND RESTART WITH 1; 
ALTER SEQUENCE TICKETSNUM_PAYMENT RESTART WITH 1;
ALTER SEQUENCE TICKETSNUM_PREVIEW RESTART WITH 1;

